/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

def upperBound = 4000000
def fibPrevious = 1, fib = 2
def sum = 0

while (fib < upperBound) {
	if (fib % 2 == 0){
		sum = sum + fib
		println sum
	}

	def tmp = fib
	fib = fibPrevious + fib
	fibPrevious = tmp
}

print sum
